#!/usr/bin/env bash
# Regression test for .github/scripts/sign.py — five fail-closed controls.
#
# sign.py signs release artifacts with the org Ed25519 key. It refuses to
# produce a signature in five places; this fixture walks every one of them
# and the happy path. Every rejection test asserts WHICH rejection (a
# distinctive fragment of the message on stderr), so an exit-1 from a
# different guard does not silently satisfy it.
#
# Run from the repo root:
#	bash tests/fixtures/releases/test-sign.sh
set -euo pipefail

# __file__ is tests/fixtures/releases/test-sign.sh; walk three levels up to
# land on the repo root regardless of where the script is invoked from.
REPO_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
# SIGN_PY_OVERRIDE lets a sabotage run point the test at a copy of
# sign.py in a tmpdir (see findings/02-red-runs.md). Production runs and
# CI never set it; the test defaults to the in-tree script.
SIGN_PY="${SIGN_PY_OVERRIDE:-$REPO_ROOT/.github/scripts/sign.py}"

PYTHON_PRESENT=0
if command -v python3 >/dev/null 2>&1 \
	&& python3 -c "from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey" 2>/dev/null; then
	PYTHON_PRESENT=1
fi
if [[ $PYTHON_PRESENT -ne 1 ]]; then
	echo "SKIP: python3 with 'cryptography' is not installed" >&2
	exit 0
fi

fail() {
	echo "FAIL: $*" >&2
	exit 1
}

# Run sign.py with GLYNDOR_RELEASE_ED25519_KEY=$1 (raw base64 of a 32-byte seed)
# and the input file at $2. Captures stdout/stderr/rc without aborting the
# script (the caller asserts on each).
#
# A real key is generated by the caller inside an isolated temp directory;
# the env var only ever holds a test key and the directory is cleaned up in
# the trap, so no real signing material survives the run.
run_sign() {
	local seed_b64="$1"
	local input_file="$2"
	local sig_file="${3:-}"
	local stdout_file="$4"
	local stderr_file="$5"

	# shellcheck disable=SC2086 # $sig_file is empty by design for the no-sig-arg case.
	if [[ -n "$sig_file" ]]; then
		env GLYNDOR_RELEASE_ED25519_KEY="$seed_b64" python3 "$SIGN_PY" "$input_file" "$sig_file" \
			>"$stdout_file" 2>"$stderr_file"
	else
		env GLYNDOR_RELEASE_ED25519_KEY="$seed_b64" python3 "$SIGN_PY" "$input_file" \
			>"$stdout_file" 2>"$stderr_file"
	fi
}

# Build a fresh 32-byte Ed25519 seed, write its base64 (canonical, no
# padding) into $1, and stash the raw bytes + the matching public key for
# later verification. The whole thing lives in a tmpdir the caller owns.
gen_test_key() {
	local seed_b64_file="$1"
	local seed_raw_file="$2"
	local pub_raw_file="$3"
	python3 - "$seed_b64_file" "$seed_raw_file" "$pub_raw_file" <<'PY'
import base64
import sys

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives import serialization

seed_b64_file, seed_raw_file, pub_raw_file = sys.argv[1:4]
# Real, fresh keypair generated inside the test. Never persisted outside
# the caller's tmpdir. Deterministic seeding would only matter if two
# concurrent runs in the same tmpdir collided; the tmpdir is unique.
sk = Ed25519PrivateKey.generate()
# private_bytes with TraditionalOpenSSL + NoEncryption returns the 32-byte
# seed prefixed by a 16-byte PKCS#8 header for a total of 48 bytes; the
# 32-byte seed sits at the END (the cryptography docs pin this). We use
# the public_key().public_bytes() form instead — it is stable across
# cryptography versions — and we derive the matching seed by re-running
# `from_private_bytes` on a chosen 32-byte input. See below.
pk_raw = sk.public_key().public_bytes(
	serialization.Encoding.Raw,
	serialization.PublicFormat.Raw,
)
# Build a 32-byte seed from sk. cryptography >=42 exposes
# `private_bytes(Raw, Raw, NoEncryption)` which is the bare 32-byte seed
# — try that first, fall back to deriving from the public key only when
# the installed version does not support the Raw/Raw form.
try:
	seed = sk.private_bytes(
		serialization.Encoding.Raw,
		serialization.PrivateFormat.Raw,
		serialization.NoEncryption(),
	)
except ValueError:
	# Older cryptography: take the last 32 bytes of the TraditionalOpenSSL
	# blob. cryptography has documented that layout since 3.0.
	seed = sk.private_bytes(
		serialization.Encoding.DER,
		serialization.PrivateFormat.TraditionalOpenSSL,
		serialization.NoEncryption(),
	)[-32:]
assert len(seed) == 32, f"unexpected seed length: {len(seed)}"
with open(seed_b64_file, "w", encoding="utf-8") as f:
	f.write(base64.b64encode(seed).decode().rstrip("="))
with open(seed_raw_file, "wb") as f:
	f.write(seed)
with open(pub_raw_file, "wb") as f:
	f.write(pk_raw)
PY
}

# -----------------------------------------------------------------------------
# Part 1: argv<2 → prints usage, exit 1.
# -----------------------------------------------------------------------------
echo "Part 1: argv<2 prints usage and exits 1"

tmp1=""
tmp5=""
trap 'rm -rf "$tmp1" "$tmp5"' EXIT

tmp1="$(mktemp -d)"
stdout1="$tmp1/out" stderr1="$tmp1/err"
set +e
python3 "$SIGN_PY" >"$stdout1" 2>"$stderr1"
rc=$?
set -e
[[ $rc -eq 1 ]] || fail "expected exit 1 for argv<2, got $rc"
# Usage is the script's __doc__. The distinctive fragment is the "Usage:" line
# plus the description of how the key is passed — both must appear.
grep -q "^Usage:" "$stderr1" || fail "expected 'Usage:' on stderr, got: $(cat "$stderr1")"
grep -q "GLYNDOR_RELEASE_ED25519_KEY" "$stderr1" || fail "expected 'GLYNDOR_RELEASE_ED25519_KEY' on stderr (the env var it explains), got: $(cat "$stderr1")"
echo "  OK    argv<2 → exit 1 with usage on stderr"

# -----------------------------------------------------------------------------
# Part 2: GLYNDOR_RELEASE_ED25519_KEY unset (or empty after strip) → exit 1
# with the 'refusing to publish an unsigned artifact' fragment.
#
# Three sub-cases, all must hit the same guard:
#   2a. env var unset (no GLYNDOR_RELEASE_ED25519_KEY in env at all)
#   2b. env var set to empty string
#   2c. env var set to whitespace only (must be stripped before the check)
# -----------------------------------------------------------------------------
echo "Part 2: missing/empty/whitespace key → exit 1 with 'refusing to publish'"

printf 'data-to-be-signed' > "$tmp1/data"
for case in unset empty whitespace; do
	stdout2="$tmp1/out_$case" stderr2="$tmp1/err_$case"
	case $case in
	unset)
		# Invoke sign.py without the env var set at all. `env -u` removes
		# it from the inherited environment so a parent's value cannot
		# leak through.
		set +e
		env -u GLYNDOR_RELEASE_ED25519_KEY python3 "$SIGN_PY" "$tmp1/data" \
			>"$stdout2" 2>"$stderr2"
		rc=$?
		set -e
		;;
	empty)
		set +e
		env GLYNDOR_RELEASE_ED25519_KEY="" python3 "$SIGN_PY" "$tmp1/data" \
			>"$stdout2" 2>"$stderr2"
		rc=$?
		set -e
		;;
	whitespace)
		# Three spaces — the .strip() in sign.py must turn this into ""
		# before the `if not seed_b64` check fires.
		set +e
		env GLYNDOR_RELEASE_ED25519_KEY="   " python3 "$SIGN_PY" "$tmp1/data" \
			>"$stdout2" 2>"$stderr2"
		rc=$?
		set -e
		;;
	esac
	[[ $rc -eq 1 ]] || fail "case $case: expected exit 1, got $rc"
	# The distinctive fragment is the full refusal sentence. The brief
	# asks for "refusing to publish an unsigned artifact"; assert it
	# verbatim, not a synonym.
	grep -q "refusing to publish an unsigned artifact" "$stderr2" \
		|| fail "case $case: expected 'refusing to publish an unsigned artifact' on stderr, got: $(cat "$stderr2")"
done
echo "  OK    unset / empty / whitespace all hit the refusal guard"

# -----------------------------------------------------------------------------
# Part 3: the seed is not valid base64. validate=True must reject URL-safe
# -/_ and stray characters (both are rejected by strict b64 decoding).
#
# The fixture must be valid in every other respect — the same input file,
# the same invocation shape — so the rejection is unambiguously about the
# base64 shape.
#
# Three sub-cases:
#   3a. URL-safe '-' in the body (standard base64 has '+' there; '-' is
#       not a valid character under validate=True)
#   3b. URL-safe '_' in the body (standard base64 has '/' there)
#   3c. a stray '!' in the body (not in either alphabet)
# -----------------------------------------------------------------------------
echo "Part 3: non-base64 seed → exit 1 with 'is not valid base64'"

# A well-formed seed in the env, then replace one character with each of
# the three bad ones in turn. The shape is otherwise the canonical
# 43-char unpadded form (32 raw bytes), generated by gen_test_key.
seed_b64_file="$tmp1/seed.b64" seed_raw_file="$tmp1/seed.raw" pub_raw_file="$tmp1/pub.raw"
gen_test_key "$seed_b64_file" "$seed_raw_file" "$pub_raw_file"
GOOD_SEED="$(cat "$seed_b64_file")"
[[ ${#GOOD_SEED} -eq 43 ]] || fail "test setup: expected 43-char unpadded base64, got ${#GOOD_SEED}"

# Build the padded canonical form (44 chars). sign.py's padding formula
# is `pad = "=" * (-len(seed_b64) % 4)`, so a 44-char input gets no
# further padding. This is the form we use to construct bad seeds: a
# `-`/`_`/`!` inserted anywhere yields a 45-char string that
#   * validate=True rejects outright ("Only base64 data is allowed")
#   * validate=False ACCEPTS — the lenient decoder drops the stray
#     character and decodes the remaining 44 chars (with the trailing
#     '=') to 32 bytes. This discrimination is what the test proves:
#     the guard fails closed ONLY because validate=True is set.
GOOD_SEED_PADDED="${GOOD_SEED}="

for case in dash underscore stray; do
	case $case in
	dash)		BAD_SEED="${GOOD_SEED_PADDED:0:5}-${GOOD_SEED_PADDED:5}" ;;
	underscore)	BAD_SEED="${GOOD_SEED_PADDED:0:5}_${GOOD_SEED_PADDED:5}" ;;
	stray)		BAD_SEED="${GOOD_SEED_PADDED:0:5}!${GOOD_SEED_PADDED:5}" ;;
	esac
	stderr3="$tmp1/err_b64_$case" stdout3="$tmp1/out_b64_$case"
	set +e
	env GLYNDOR_RELEASE_ED25519_KEY="$BAD_SEED" python3 "$SIGN_PY" "$tmp1/data" \
		>"$stdout3" 2>"$stderr3"
	rc=$?
	set -e
	[[ $rc -eq 1 ]] || fail "case $case: expected exit 1, got $rc"
	# The distinctive fragment: "is not valid base64" — this is the
	# branch's error prefix. Asserting only "exit 1" would be satisfied
	# by the length-guard below, which is a different guard.
	grep -q "is not valid base64" "$stderr3" \
		|| fail "case $case: expected 'is not valid base64' on stderr, got: $(cat "$stderr3")"
done

# Acceptance-of-the-same-shape: a seed that IS valid base64 and IS 32 bytes
# (the well-formed one we just generated) does NOT hit the base64 guard. It
# reaches the length guard or the happy path; for the control to be precise,
# the test only needs to prove the bad-base64 branch fired for the bad
# inputs above and that the same shape just inside the limit (32 raw bytes,
# valid b64) is not classified as bad-base64.
# Build a 32-byte seed that decodes to exactly 32 bytes, run it, and
# confirm the base64 guard did NOT fire. Either the length guard fires
# (which it shouldn't, since it's exactly 32) or we reach the happy path.
stderr3_ok="$tmp1/err_b64_ok" stdout3_ok="$tmp1/out_b64_ok"
set +e
env GLYNDOR_RELEASE_ED25519_KEY="$GOOD_SEED" python3 "$SIGN_PY" "$tmp1/data" \
	>"$stdout3_ok" 2>"$stderr3_ok"
rc_ok=$?
set -e
if [[ $rc_ok -eq 1 ]] && grep -q "is not valid base64" "$stderr3_ok"; then
	fail "valid 32-byte seed must not hit the bad-base64 guard (stderr: $(cat "$stderr3_ok"))"
fi
echo "  OK    bad-base64 seed rejected; valid 32-byte seed passes the base64 guard"

# -----------------------------------------------------------------------------
# Part 4: the decoded seed is not exactly 32 bytes.
#
# The guard says `len(seed) != 32`. We exercise both sides of the
# boundary (31 and 33 bytes). Every rejection must produce the 'must
# decode to 32 bytes' fragment on stderr. The bad-length seed must be
# valid base64 (otherwise the base64 guard above fires and the test
# proves nothing about length).
#
# Pair: a 32-byte seed (the well-formed one) MUST NOT hit the length
# guard.
# -----------------------------------------------------------------------------
echo "Part 4: wrong-length seed → exit 1 with 'must decode to 32 bytes'"

# Build a deterministic N-byte raw seed and base64-encode it (trivially
# valid base64 — the rejection is solely about length). The seed bytes
# are not a real key; the test only cares that the length-guard fires.
gen_wrong_len() {
	local out_var="$1" raw_len="$2"
	python3 - "$out_var" "$raw_len" <<'PY'
import base64, sys
out_var, raw_len = sys.argv[1], int(sys.argv[2])
seed = bytes(range(raw_len))
encoded = base64.b64encode(seed).decode().rstrip("=")
# Stash in a temp file so the bash side can read it back without quoting
# headaches.
import tempfile
f = tempfile.NamedTemporaryFile("w", delete=False, suffix=".b64")
f.write(encoded)
f.close()
print(f.name)
PY
}

for raw_len in 31 33; do
	bad_seed_file="$(gen_wrong_len "$raw_len" "$raw_len")"
	BAD_SEED="$(cat "$bad_seed_file")"
	rm -f "$bad_seed_file"
	stderr4="$tmp1/err_len_${raw_len}" stdout4="$tmp1/out_len_${raw_len}"
	set +e
	env GLYNDOR_RELEASE_ED25519_KEY="$BAD_SEED" python3 "$SIGN_PY" "$tmp1/data" \
		>"$stdout4" 2>"$stderr4"
	rc=$?
	set -e
	[[ $rc -eq 1 ]] || fail "raw_len=$raw_len: expected exit 1, got $rc"
	# The distinctive fragment: "must decode to 32 bytes". Asserting
	# only "exit 1" would be satisfied by the bad-base64 guard above,
	# which is a different guard.
	grep -q "must decode to 32 bytes" "$stderr4" \
		|| fail "raw_len=$raw_len: expected 'must decode to 32 bytes' on stderr, got: $(cat "$stderr4")"
done

# Pair: a 32-byte seed MUST NOT hit the length guard. Use the same
# well-formed seed from part 3.
stderr4_ok="$tmp1/err_len_ok" stdout4_ok="$tmp1/out_len_ok"
set +e
env GLYNDOR_RELEASE_ED25519_KEY="$GOOD_SEED" python3 "$SIGN_PY" "$tmp1/data" \
	>"$stdout4_ok" 2>"$stderr4_ok"
rc_ok=$?
set -e
if [[ $rc_ok -eq 1 ]] && grep -q "must decode to 32 bytes" "$stderr4_ok"; then
	fail "valid 32-byte seed must not hit the length guard (stderr: $(cat "$stderr4_ok"))"
fi
echo "  OK    31/33-byte seeds rejected with 'must decode to 32 bytes'; 32-byte seed passes the length guard"

# -----------------------------------------------------------------------------
# Part 5: happy path. sign.py writes a detached signature, and the
# signature verifies against the public key derived from the same seed.
#
# A file-exists assertion would pass for a signature of the wrong bytes
# (e.g. one made with a different key). The test therefore re-derives the
# public key from the seed and verifies the signature under it — the same
# loop a consumer (install.sh / install.ps1 / internal/update/verify.rs)
# would run on a freshly signed release.
# -----------------------------------------------------------------------------
echo "Part 5: happy path writes a signature that verifies under the matching key"

tmp5="$(mktemp -d)"
seed_b64_file5="$tmp5/seed.b64" seed_raw_file5="$tmp5/seed.raw" pub_raw_file5="$tmp5/pub.raw"
gen_test_key "$seed_b64_file5" "$seed_raw_file5" "$pub_raw_file5"
GOOD_SEED5="$(cat "$seed_b64_file5")"
printf 'fixture-payload-for-sign.py-test' > "$tmp5/data"

# Default output path: <input>.sig — exercise that branch.
stderr5="$tmp5/err" stdout5="$tmp5/out"
set +e
run_sign "$GOOD_SEED5" "$tmp5/data" "" "$stdout5" "$stderr5"
rc=$?
set -e
[[ $rc -eq 0 ]] || fail "happy path (default sig path): expected exit 0, got $rc (stderr: $(cat "$stderr5"))"
[[ -s "$tmp5/data.sig" ]] || fail "happy path: expected $tmp5/data.sig to exist and be non-empty"

# Verify the signature. A file-exists assertion would pass a wrong-key
# signature; this is what the consumers actually do, so the test mirrors
# them. The signature MUST verify under the public key derived from the
# seed that sign.py used. The pubkey is 32 raw bytes — round-tripping it
# through bash $() would mangle non-printable bytes, so we pass the file
# path and let python read it.
verify_out="$tmp5/verify_out" verify_err="$tmp5/verify_err"
set +e
python3 - "$tmp5/data.sig" "$tmp5/data" "$pub_raw_file5" >"$verify_out" 2>"$verify_err" <<'PY'
import sys
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
from cryptography.exceptions import InvalidSignature
sig_file, data_file, pub_raw_file = sys.argv[1], sys.argv[2], sys.argv[3]
sig = open(sig_file, "rb").read()
data = open(data_file, "rb").read()
pk_raw = open(pub_raw_file, "rb").read()
try:
	Ed25519PublicKey.from_public_bytes(pk_raw).verify(sig, data)
except InvalidSignature as exc:
	sys.exit(f"signature did not verify under the matching public key: {exc}")
print("verified")
PY
verify_rc=$?
set -e
[[ $verify_rc -eq 0 ]] || fail "happy path: signature did not verify under the matching public key ($(cat "$verify_err"))"
grep -q "^signed " "$stdout5" || fail "happy path: expected 'signed …' on stdout, got: $(cat "$stdout5")"
echo "  OK    default <input>.sig path: signature verifies under matching public key"

# Explicit output path: also exercise the optional second argument. A
# different sig file lives at a caller-chosen path, the signature in it
# verifies, and the default <input>.sig does NOT exist (so a regression
# that ignores argv[2] would write to the default anyway and we'd notice
# because the file would still be empty for the explicit path).
EXPLICIT_SIG="$tmp5/explicit.sig"
stderr5b="$tmp5/err_b" stdout5b="$tmp5/out_b"
set +e
run_sign "$GOOD_SEED5" "$tmp5/data" "$EXPLICIT_SIG" "$stdout5b" "$stderr5b"
rc=$?
set -e
[[ $rc -eq 0 ]] || fail "happy path (explicit sig path): expected exit 0, got $rc"
[[ -s "$EXPLICIT_SIG" ]] || fail "happy path: expected $EXPLICIT_SIG to be written"

# Re-verify under the matching public key. The pubkey is read from the
# file path directly (its 32 raw bytes are not safe to round-trip through
# bash $()).
set +e
python3 - "$EXPLICIT_SIG" "$tmp5/data" "$pub_raw_file5" >/dev/null 2>"$tmp5/verify_err_b" <<'PY'
import sys
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
from cryptography.exceptions import InvalidSignature
sig = open(sys.argv[1], "rb").read()
data = open(sys.argv[2], "rb").read()
pk = open(sys.argv[3], "rb").read()
try:
	Ed25519PublicKey.from_public_bytes(pk).verify(sig, data)
except InvalidSignature as exc:
	sys.exit(f"explicit-path signature did not verify: {exc}")
PY
verify_rc=$?
set -e
[[ $verify_rc -eq 0 ]] || fail "happy path (explicit sig): signature did not verify under the matching public key"
echo "  OK    explicit <sig> path: signature verifies under matching public key"

# Pair: a signature made with a DIFFERENT key (a fresh generate()) does
# NOT verify under the public key derived from GOOD_SEED5. This is the
# negative-control: the test's verify step is real, not a tautology that
# would accept any 64-byte file.
WRONG_SIG="$tmp5/wrong.sig"
python3 - "$tmp5/data" "$WRONG_SIG" <<'PY'
import sys
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
data = open(sys.argv[1], "rb").read()
# Fresh keypair, unrelated to GOOD_SEED5.
sig = Ed25519PrivateKey.generate().sign(data)
open(sys.argv[2], "wb").write(sig)
PY
set +e
python3 - "$WRONG_SIG" "$tmp5/data" "$pub_raw_file5" >/dev/null 2>"$tmp5/wrong_err" <<'PY'
import sys
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
from cryptography.exceptions import InvalidSignature
sig = open(sys.argv[1], "rb").read()
data = open(sys.argv[2], "rb").read()
pk = open(sys.argv[3], "rb").read()
try:
	Ed25519PublicKey.from_public_bytes(pk).verify(sig, data)
	sys.exit("negative-control: a signature under a different key VERIFIED under our public key — the test would prove nothing")
except InvalidSignature:
	pass
PY
neg_rc=$?
set -e
[[ $neg_rc -eq 0 ]] || fail "negative control: a signature under a fresh key should not verify under GOOD_SEED5's pubkey"
echo "  OK    negative control: wrong-key signature does not verify under the matching public key"

echo
echo "All parts passed."
