name: DCO

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  dco:
    uses: Glyndor/.github/.github/workflows/dco.yml@76f8bc6dd79baa995d5bfa347c4b985433cb0ce1 # v1.20.0
