name: Lint shell scripts

on:
  push:
    branches:
      - develop
    paths:
      - "**.sh"
      - ".github/workflows/lint-shell.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "**.sh"
      - ".github/workflows/lint-shell.yml"

permissions:
  contents: read

jobs:
  shellcheck:
    uses: Glyndor/.github/.github/workflows/shell-ci.yml@e61aaf0e920345b3dbb82cacd3bd36a499951a92 # v1.13.0
