name: Lint shell scripts

on:
  push:
    branches:
      - develop
    paths:
      - "**.sh"
      - ".github/workflows/lint-shell.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "**.sh"
      - ".github/workflows/lint-shell.yml"

permissions:
  contents: read

jobs:
  shellcheck:
    uses: Glyndor/.github/.github/workflows/shell-ci.yml@76f8bc6dd79baa995d5bfa347c4b985433cb0ce1 # v1.20.0
