name: guard

on:
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  develop-only:
    uses: Glyndor/.github/.github/workflows/main-guard.yml@e70ff47fd8aefa0f054846815f19b98768d61122 # v1.17.0
