name: guard

on:
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  develop-only:
    uses: Glyndor/.github/.github/workflows/main-guard.yml@76f8bc6dd79baa995d5bfa347c4b985433cb0ce1 # v1.20.0
