name: Supply chain

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "about.toml"
      - "about.hbs"
      - ".github/workflows/supply-chain.yml"
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  supply-chain:
    uses: Glyndor/.github/.github/workflows/rust-supply-chain.yml@c958978687af37dc2d826a967d9c549589afb39f # v1.14.1
