name: Supply chain

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "about.toml"
      - "about.hbs"
      - ".github/workflows/supply-chain.yml"
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  supply-chain:
    uses: Glyndor/.github/.github/workflows/rust-supply-chain.yml@d5041b038b7d4935e75400dff612962e6fa14893 # v1.21.0
