name: Workflow lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  workflow-lint:
    uses: Glyndor/.github/.github/workflows/workflow-lint.yml@fadfbebc989a58a2292438fecbd5a616ffa0bdf3 # v1.15.0
