name: Workflow lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  workflow-lint:
    uses: ./.github/workflows/reusable-workflow-lint.yml
